In [1]:
import numpy as np 

In [2]:
#Create a null vector of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#Create a null vector of size 10 but the fifth value which is 1
n= np.zeros(10)
n[5]= 1
print(n)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [4]:
#Create a vector with values ranging from 10 to 49
n = np.arange(10,50)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#Reverse a vector (the first element becomes last)
n = n[::-1]
print(n)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [7]:
#Create a 3x3 matrix with values ranging from 0 to 8
Mat = np.arange(9).reshape(3,3)
print(Mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#Find indices of non­zero elements from [1,2,0,0,4,0]
n = np.array([1,2,0,0,4,0])
np.nonzero(n)


(array([0, 1, 4], dtype=int64),)

In [13]:
#Create a 3x3x3 array with random values
Mat1 =  np.random.random((3,3,3))
print(Mat1)

[[[0.8291724  0.78765285 0.64914211]
  [0.20338304 0.0943906  0.23794112]
  [0.97314296 0.66032434 0.94729962]]

 [[0.00874659 0.05916917 0.54331372]
  [0.87285725 0.0486524  0.95520986]
  [0.07254711 0.52795831 0.55070597]]

 [[0.6956574  0.39005217 0.41638399]
  [0.25325381 0.45470903 0.14996069]
  [0.60142952 0.12022825 0.40349916]]]


In [15]:
#Create a random vector of size 30 and find the mean value
V= np.random.random((30))
print(V)
print(V.mean())


[0.66905896 0.54466235 0.16833997 0.28261151 0.30504291 0.01380364
 0.67778186 0.10507321 0.91583742 0.02962391 0.61513847 0.26691464
 0.55248279 0.33490618 0.14913    0.45681951 0.3515867  0.62838204
 0.74011023 0.50982147 0.50700192 0.68770431 0.36601803 0.96924952
 0.72433988 0.95997805 0.08021221 0.91782503 0.23345349 0.16131001]
0.4641406737801905


In [17]:
#Create a 2d array with 1 on the border and 0 inside
x = np.ones((4,4))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [4]:
#Create an 8x8 matrix and fill it with a checkerboard pattern
import numpy as np
x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#What is the major difference between sets, lists, tuples and dictionaries?
Lists are mutable and represented by sqaure brackets . 
Tuple are immutable and represented by parenthsis 
sets  - Sets are mutuable , ordered and represented by curly braces
Dictioneries  - It holds the key and value 


In [5]:
#Print first 10 natural numbers using while loop

i =1
print("First 10 natural numbers are :")
while i <11:
    print(i)
    i += 1

First 10 natural numbers are :
1
2
3
4
5
6
7
8
9
10


In [10]:
#Print the numbers -10 to -1 using for loop.
for i in range (-10,0,1):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [12]:
#Print the message “Done” after successful execution of any for a loop.
for i in range (-10,0,1):
    print(i)
print("Done")

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
Done


In [25]:
#Create a random vector of size 10 and sort it
import numpy as np 
n = np.random.random(10)
a = n.sort()
print(a)


None


In [29]:
#Execute any three math functions using NumPy.
n= np.array([60,45,90,270,180])
print(n)
print("sin function ")
print(np.sin(n))
print("cosine function ")
print(np.cos(n))
a1 = np.array ([20.3,40.50,39.22])
print("Round value ")
print(np.around(a1))

[ 60  45  90 270 180]
sin function 
[-0.30481062  0.85090352  0.89399666 -0.17604595 -0.80115264]
cosine function 
[-0.95241298  0.52532199 -0.44807362  0.98438195 -0.59846007]
Round value 
[20. 40. 39.]
